sudo: required\
language: generic
services:
  - docker

before_install:
  - docker build -t johndarragh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true johndarragh/docker-react npm run test -- --coverage
