sudo: required\
language: generic
services:
  - docker

before_install:
  - docker build -t johndarragh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true johndarragh/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-514305968389"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
